name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Read versions
        id: set-matrix
        run: python3 scripts/read_versions.py

  build-and-push:
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.get-versions.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.template
          build-args: |
            DOXYGEN_VERSION=${{ matrix.version }}
          tags: ${{ vars.DOCKER_USERNAME }}/doxygen:${{ matrix.version }}
          load: true

      - name: Test
        run: |
          docker run --rm ${{ vars.DOCKER_USERNAME }}/doxygen:${{ matrix.version }} doxygen --version

      - name: Push Docker image
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/doxygen:${{ matrix.version }}
