name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight

jobs:
  get-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Read versions
        id: set-matrix
        run: |
          python3 scripts/read_versions.py

  build:
    needs: get-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.get-versions.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ vars.DOCKER_USERNAME }}/doxygen:${{ matrix.version }}
          outputs: type=docker,dest=/tmp/doxygen-${{ matrix.version }}.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-${{ matrix.version }}
          path: /tmp/doxygen-${{ matrix.version }}.tar

  push:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [get-versions, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJson(needs.get-versions.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: doxygen-${{ matrix.version }}
          path: /tmp/doxygen-${{ matrix.version }}.tar

      - name: Load Docker image
        run: |
          docker load --input /tmp/doxygen-${{ matrix.version }}.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/doxygen:${{ matrix.version }}
